apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
  id_rsa: <copy-paste the output of: cat ~/.ssh/id_rsa | base64 -w0>
  known_hosts: <copy-paste the output of: ssh-keyscan github.com | base64 -w 0>