# tekton task example
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: hello-task
      image: ubuntu:latest
      command:
        - /bin/bash
      args: ['-c', 'echo Hello Tekton']
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: task-run
spec:
  taskRef:
    name: hello